dist: bionic
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

env:
  global:
  - NJOBS=3
  - COMPILER="4.11.1"
  matrix:
  - COQ_VER="8.13.0" REPO_NAME="coq-released"  REPO_URL="http://coq.inria.fr/opam/released"

install:
- export OPAMROOT=$HOME/.opam
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam repo add coq-core-dev https://coq.inria.fr/opam/core-dev || echo "coq-core-dev registered"
- opam repo add "${REPO_NAME}" "${REPO_URL}" || echo "${REPO_NAME} registered"
- travis_wait opam install coq.${COQ_VER} -y
- opam pin add -y -n T2048 .
- opam install -y -vvv --deps-only T2048

script:
 - make -j ${NJOBS}
 - make install
